### ISSUE TITLE
Does this have Quicksign?

### ISSUE THREAD

**Issue by tim-eucalyptus** [kadena-io/wallet-connect-example#2]
I couldn't see reference to it in the code anywhere.

**Comment by ash-vd** [comment]
Not yet, but will be added :)

**Comment by ash-vd** [comment]
Quicksign has been added, see [here](https://github.com/kadena-io/wallet-connect-example/blob/main/src/components/Transaction.tsx#L107) and [quickSignWithWalletConnect.tsx](https://github.com/kadena-community/kadena.js/blob/feat/3-phase-tr/packages/libs/client/src/signing/walletconnect/quicksignWithWalletConnect.ts)
